### ISSUE TITLE
Switch to semantic versioning

### ISSUE THREAD

**Issue by christ2go** [SuperTux/addons#18]
Currently the version number is an integer, which should get updated, whenever a change is made to the addon. But when only a small fix is done, it might seen a bit odd to increment the version number by one. Therefore it might be an idea to switch to semantic versioning.
# Pro
+ A small change only leads to a small change in the version number
+ Checking if you have the leatest version can be done via the number and not the md5-hash (don't really know if it's a pro)

# Contra
+ For non-developers the integer versioning scheme might be easier to understand

As for implementation, backward compatability should be ensured. The main question is, wether there should be new entries for "version-minor" and "version-patch", or if it should remain one field, but that would change the type to string (if I'm correct).

**Comment by Grumbel** [comment]
The only reason why there is a version number is so that the AddonManager knows when there is a new version of an AddOn. It's not meant to be human readable or pretty looking and there would be no benefit to that.

The MD5 is not used to check for new versions, it is only used to ensure that the download was successful.

If there is a case in which an AddOn badly breaks compatibility, it can be given a different addon-id and uploaded as a new AddOn.

**Comment by maxteufel** [comment]
> The MD5 is not used to check for new versions, it is only used to ensure that the download was successful.

It is being used. See SuperTux/supertux@f72cd831. I recently verified this using a test server since I wasn't sure whether or not updated translation packs would show up as updates in the game (they're always version 1).
