### ISSUE TITLE
Hume's rainbow cave: Overworld is covered by forest when playing again

### ISSUE THREAD

**Issue by Wuzzy2** [SuperTux/addons#8]
Bug in Hume's rainbow cave in SuperTux 0.4.0:

If you return to the main crystal cave island from the main menu, first everything is covered by a forest. You first have to move Tux somewhere to make the forest “insivible” again.
I am assuming Tux was already in the crystal cave island, not on the starting land.

**Comment by maxteufel** [comment]
Assigning all of #8, #9 and #10 to @Hume2. If they don't want to fix that, sorry. We don't provide official support for add-ons (else they would be part of the game).

**Comment by LMH0013** [comment]
This is still occurring.  In addition, the bonus map position is not preserved upon exit.  It's not too bad of a bug, but it does look weird.

**Comment by Hume2** [comment]
It's a SuperTux bug that it doesn't remember the position on the bonus island, not bug of this addon.

**Comment by LMH0013** [comment]
You are right.  SuperTux currently doesn't support multiple worldmaps, at least not entirely.  Most of the mechanisms are already there, but it requires some creative scripting to get it to work correctly.  The problem is that the main worlmap is loaded by default, not the worlmap that was last played.  So in this case, Tux spawns on the edge of the first worldmap, which automatically loads the bonus map at the start position.  I wouldn't blame you for not wanting to tweak it, nor do I think it's important enough to spend the time.  I just thought you might like to know that you're world was misbehaving.

Having everything covered on startup is more of an issue, you can't even tell where you are at unless you move the correct direction which differs from point to point.  That bug is worth fixing.

**Comment by Hume2** [comment]
It no longer happens since I've fixed that worldmap bug.
